# Site settings
title: Css loaders
name: Disjfa valours
email: disjfa@disjfa.com
description: >
  Css loaders
baseurl: ""
url: "https://disjfa.github.io"
github_url:  https://github.com/disjfa/css-loaders
github_username:  disjfa

# Google
google_analytics:

# Build settings
markdown: kramdown

# deployment
source: site
host: 0.0.0.0
port: 5000
